version: '3'
services:
  node-app:
    build: .
    image: node-app
    container_name: node_app
    command: npm run dev
    # env_file: .env
    environment:
      - MONGODB_URI=mongodb://mongodb:27017/node-boilerplate
      # - MONGO_USERNAME=$MONGO_USERNAME
      # - MONGO_PASSWORD=$MONGO_PASSWORD
      # - MONGO_HOSTNAME=db
      # - MONGO_PORT=$MONGO_PORT
      # - MONGO_DB=$MONGO_DB
    ports:
      - '3000:3000'
    depends_on:
      - mongodb
    volumes:
      - .:/var/www
    networks:
      - node-network
  mongodb:
    image: mongo
    container_name: mongodb
    hostname: mongo
    ports:
      - 27017:27017
    networks:
      - node-network
  mongo-express:
    image: mongo-express
    container_name: mongo_express
    links:
      - mongodb
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_SERVER: mongodb
      ME_CONFIG_MONGODB_PORT: 27017
    networks:
      - node-network
  redis:
    image: redis:alpine
    container_name: redis
    privileged: true
    ports:
      - 6379:6379
    networks:
      - node-network
  swaggerui:
    image: swaggerapi/swagger-ui
    container_name: swagger_api
    environment:
      - API_URL=./index-api.yaml
    volumes:
      - ./docs/openapi.yaml:/usr/share/nginx/html/index-api.yaml
    ports:
      - '8080:8080'
    networks:
      - node-network
volumes:
  dbdata:
  node_modules:

networks:
  node-network:
    driver: bridge
